<!--EconomicTrendsPolLESSIRE.shared-->

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\EconomicTrendsPolLESSIRE.Contracts\EconomicTrendsPolLESSIRE.Contracts\EconomicTrendsPolLESSIRE.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Extensions\" />
		<Folder Include="Json\" />
		<Folder Include="Utils\" />
		<Folder Include="Notifications\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
		<PackageReference Include="Polly" Version="8.7.0" />
	</ItemGroup>

</Project>
