<!--EconomicTrendsPolLESSIRE.Hubs-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Filters\" />
    <Folder Include="StaticConfig\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
	  <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\..\EconomicTrendsPolLESSIRE.Contracts\EconomicTrendsPolLESSIRE.Contracts\EconomicTrendsPolLESSIRE.Contracts.csproj" />
	  <ProjectReference Include="..\EconomicTrendsPolLESSIRE.Application\EconomicTrendsPolLESSIRE.Application.csproj" />
	<ProjectReference Include="..\EconomicTrendsPolLESSIRE.Shared\EconomicTrendsPolLESSIRE.Shared.csproj" />
	<ProjectReference Include="..\EconomicTrendsPolLESSIRE.DTOs\EconomicTrendsPolLESSIRE.DTOs.csproj" />
  </ItemGroup>

</Project>
