<!--EconomicTrendsPolLESSIRE.Application-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CQRS\Commands\Handlers\" />
    <Folder Include="CQRS\Queries\Handlers\" />
    <Folder Include="CQRS\Queries\Validations\" />
    <Folder Include="DTOs\" />
    <Folder Include="Interfaces\ExternalProviders\" />
    <Folder Include="Models\" />
    <Folder Include="Mongo\" />
    <Folder Include="Mistral\" />
    <Folder Include="Time\" />
    <Folder Include="Services\" />
    <Folder Include="Options\" />
    <Folder Include="Notifications\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Polly" Version="8.7.0" />
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="10.6.0" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\..\EconomicTrendsPolLESSIRE.Contracts\EconomicTrendsPolLESSIRE.Contracts\EconomicTrendsPolLESSIRE.Contracts.csproj" />
	  <ProjectReference Include="..\EconomicTrendsPolLESSIRE.Domain\EconomicTrendsPolLESSIRE.Domain.csproj" />
	  <ProjectReference Include="..\EconomicTrendsPolLESSIRE.Shared\EconomicTrendsPolLESSIRE.Shared.csproj" />
	  <ProjectReference Include="..\EconomicTrendsPolLESSIRE.Hubs\EconomicTrendsPolLESSIRE.Hubs.csproj" />
  </ItemGroup>

</Project>
