<!--EconomicTrendsPolLESSIRE.API-->

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>56c60060-d30b-48a0-b962-546726763fe1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" Version="1.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.31" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.30" />
	<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.3" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.22.0" />
    <PackageReference Include="Polly" Version="8.7.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\EconomicTrendsPolLESSIRE.Contracts\EconomicTrendsPolLESSIRE.Contracts\EconomicTrendsPolLESSIRE.Contracts.csproj" />
		<ProjectReference Include="..\EconomicTrendsPolLESSIRE.Application\EconomicTrendsPolLESSIRE.Application.csproj" />
		<ProjectReference Include="..\EconomicTrendsPolLESSIRE.Domain\EconomicTrendsPolLESSIRE.Domain.csproj" />
		<ProjectReference Include="..\EconomicTrendsPolLESSIRE.DTOs\EconomicTrendsPolLESSIRE.DTOs.csproj" />
		<ProjectReference Include="..\EconomicTrendsPolLESSIRE.Hubs\EconomicTrendsPolLESSIRE.Hubs.csproj" />
		<ProjectReference Include="..\EconomicTrendsPolLESSIRE.Infrastructure\EconomicTrendsPolLESSIRE.Infrastructure.csproj" />
		<ProjectReference Include="..\EconomicTrendsPolLESSIRE.Shared\EconomicTrendsPolLESSIRE.Shared.csproj" />
	</ItemGroup>

  <ItemGroup>
    <Folder Include="BackgroundService\" />
    <Folder Include="BackgroundWorkers\" />
    <Folder Include="Extensions\" />
    <Folder Include="Hubs\Serilog\Sinks\" />
    <Folder Include="Middlewares\" />
    <Folder Include="Models\" />
    <Folder Include="Services\" />
    <Folder Include="Security\" />
  </ItemGroup>

</Project>
