<!--EconomicTrendsPolLESSIRE.Infrastructure-->

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>

		<ProjectReference Include="..\..\EconomicTrendsPolLESSIRE.Contracts\EconomicTrendsPolLESSIRE.Contracts\EconomicTrendsPolLESSIRE.Contracts.csproj" />
		<ProjectReference Include="..\EconomicTrendsPolLESSIRE.Application\EconomicTrendsPolLESSIRE.Application.csproj" />
		<!--<ProjectReference Include="..\EconomicTrendsPolLESSIRE.Domain\EconomicTrendsPolLESSIRE.Domain.csproj" />
		<ProjectReference Include="..\EconomicTrendsPolLESSIRE.DTOs\EconomicTrendsPolLESSIRE.DTOs.csproj" />-->
		<ProjectReference Include="..\EconomicTrendsPolLESSIRE.Shared\EconomicTrendsPolLESSIRE.Shared.csproj" />

	</ItemGroup>

	<ItemGroup>
		<Folder Include="AI\FastApi\" />
		<Folder Include="Background\" />
		<Folder Include="Dapper\" />
		<Folder Include="Extensions\" />
		<Folder Include="ExternalAPIs\" />
		<Folder Include="ExternalProviders\" />
		<Folder Include="UseCases\" />
		<Folder Include="SignalR\" />
		<Folder Include="Security\" />
		<Folder Include="Resilience\" />
		<Folder Include="Persistence\" />
		<Folder Include="Options\" />
		<Folder Include="NoSql\" />
		<Folder Include="Services\Monitoring\" />
	</ItemGroup>

</Project>
